# Generated by Django 2.0.3 on 2018-03-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidincdr',
            name='redirectingNumber',
            field=models.BigIntegerField(null=True),
        ),
    ]
