# Generated by Django 2.0.3 on 2018-03-19 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaInCdrMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueBeforeCall', models.FloatField()),
                ('valueAfterCall', models.FloatField()),
                ('createdDate', models.DateTimeField()),
                ('createdBy', models.CharField(default='Khal Drogo', max_length=100)),
                ('updatedDate', models.CharField(default='Khal Drogo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DedicatedAccount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('sub_type', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField()),
                ('createdBy', models.CharField(default='Khal Drogo', max_length=100)),
                ('updatedDate', models.CharField(default='Khal Drogo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('createdDate', models.DateTimeField()),
                ('createdBy', models.CharField(default='Khal Drogo', max_length=100)),
                ('updatedDate', models.CharField(default='Khal Drogo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrepaidInCdr',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('accountValueBeforeCall', models.FloatField()),
                ('accountValueAfterCall', models.FloatField()),
                ('callCharge', models.FloatField()),
                ('chargedDuration', models.IntegerField()),
                ('callStartTime', models.DateTimeField()),
                ('callerNumber', models.BigIntegerField()),
                ('calledNumber', models.BigIntegerField()),
                ('redirectingNumber', models.BigIntegerField(null=True)),
                ('GsmCallRefNumber', models.CharField(max_length=100)),
                ('presentationIndicator', models.IntegerField()),
                ('createdDate', models.DateTimeField()),
                ('createdBy', models.CharField(default='Khal Drogo', max_length=100)),
                ('updatedDate', models.CharField(default='Khal Drogo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceClass',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField()),
                ('createdBy', models.CharField(default='Khal Drogo', max_length=100)),
                ('updatedDate', models.CharField(default='Khal Drogo', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='prepaidincdr',
            name='serviceClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmb.ServiceClass'),
        ),
        migrations.AddField(
            model_name='daincdrmap',
            name='DedicatedAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmb.DedicatedAccount'),
        ),
        migrations.AddField(
            model_name='daincdrmap',
            name='PrepaidInCdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmb.PrepaidInCdr'),
        ),
    ]
