# Generated by Django 2.0.3 on 2018-03-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='sub_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
