# Generated by Django 2.0.3 on 2018-03-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0002_auto_20180326_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepaidincdr',
            name='GsmCallRefNumber',
        ),
        migrations.AddField(
            model_name='prepaidincdr',
            name='gsmCallRefNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='beepcdr',
            name='calledNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='beepcdr',
            name='callerNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='beepcdr',
            name='createdBy',
            field=models.CharField(default='Khal Drogo', max_length=50),
        ),
        migrations.AlterField(
            model_name='beepcdr',
            name='updatedBy',
            field=models.CharField(default='Khal Drogo', max_length=50),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='createdBy',
            field=models.CharField(default='Khal Drogo', max_length=50),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='msisdn',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='updatedBy',
            field=models.CharField(default='Khal Drogo', max_length=50),
        ),
        migrations.AlterField(
            model_name='freebies',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='freebies',
            name='createdBy',
            field=models.CharField(default='Khal Drogo', max_length=50),
        ),
        migrations.AlterField(
            model_name='freebies',
            name='updatedBy',
            field=models.CharField(default='Khal Drogo', max_length=50),
        ),
        migrations.AlterField(
            model_name='freebiestype',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='freebiestype',
            name='createdBy',
            field=models.CharField(default='Khal Drogo', max_length=50),
        ),
        migrations.AlterField(
            model_name='freebiestype',
            name='updatedBy',
            field=models.CharField(default='Khal Drogo', max_length=50),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='calledNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='callerNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='createdBy',
            field=models.CharField(default='Khal Drogo', max_length=50),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='updatedBy',
            field=models.CharField(default='Khal Drogo', max_length=50),
        ),
        migrations.AlterField(
            model_name='revenueconfig',
            name='createdBy',
            field=models.CharField(default='Khal Drogo', max_length=50),
        ),
        migrations.AlterField(
            model_name='revenueconfig',
            name='updatedBy',
            field=models.CharField(default='Khal Drogo', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='createdBy',
            field=models.CharField(default='Khal Drogo', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='updatedBy',
            field=models.CharField(default='Khal Drogo', max_length=50),
        ),
    ]
