# Generated by Django 2.0.3 on 2018-03-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0002_auto_20180323_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidincdr',
            name='revenueShared',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
