# Generated by Django 2.0.3 on 2018-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0002_auto_20180319_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='daincdrmap',
            name='updatedBy',
            field=models.CharField(default='Khal Drogo', max_length=100),
        ),
        migrations.AddField(
            model_name='dedicatedaccount',
            name='updatedBy',
            field=models.CharField(default='Khal Drogo', max_length=100),
        ),
        migrations.AddField(
            model_name='exceptionlist',
            name='updatedBy',
            field=models.CharField(default='Khal Drogo', max_length=100),
        ),
        migrations.AddField(
            model_name='prepaidincdr',
            name='updatedBy',
            field=models.CharField(default='Khal Drogo', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceclass',
            name='updatedBy',
            field=models.CharField(default='Khal Drogo', max_length=100),
        ),
        migrations.AlterField(
            model_name='daincdrmap',
            name='updatedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='updatedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='updatedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='updatedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='updatedDate',
            field=models.DateTimeField(),
        ),
    ]
