# Generated by Django 2.0.3 on 2018-03-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0003_auto_20180319_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidincdr',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
