# Generated by Django 2.0.3 on 2018-03-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0003_auto_20180323_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidincdr',
            name='redirectingNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
