# Generated by Django 2.0.3 on 2018-03-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0004_auto_20180327_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidincdr',
            name='id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
