# Generated by Django 2.0.3 on 2018-03-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0004_auto_20180321_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidincdr',
            name='calledNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='callerNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='redirectingNumber',
            field=models.IntegerField(null=True),
        ),
    ]
