# Generated by Django 2.0.3 on 2018-03-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0005_auto_20180325_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daincdrmap',
            name='valueAfterCall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daincdrmap',
            name='valueBeforeCall',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
