# Generated by Django 2.0.3 on 2018-03-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0005_auto_20180327_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daincdrmap',
            old_name='DedicatedAccount',
            new_name='dedicatedAccount',
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
