# Generated by Django 2.0.3 on 2018-03-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0005_auto_20180321_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='beepCDR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calledNumber', models.IntegerField()),
                ('callerNumber', models.IntegerField()),
                ('callStartTime', models.DateTimeField()),
                ('createdDate', models.DateTimeField()),
                ('updatedDate', models.DateTimeField()),
                ('createdBy', models.CharField(default='Khal Drogo', max_length=100)),
                ('updatedBy', models.CharField(default='Khal Drogo', max_length=100)),
            ],
        ),
    ]
