# Generated by Django 2.0.3 on 2018-03-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0006_auto_20180325_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidincdr',
            name='redirectingNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
