# Generated by Django 2.0.3 on 2018-03-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0006_beepcdr'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidincdr',
            name='revenueShared',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
