# Generated by Django 2.0.3 on 2018-03-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0007_prepaidincdr_revenueshared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidincdr',
            name='revenueShared',
            field=models.FloatField(null=True),
        ),
    ]
