# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0008_auto_20180329_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkLoader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.FileField(upload_to=b'bulkfile')),
            ],
        ),
    ]
