# Generated by Django 2.0.3 on 2018-03-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0008_auto_20180325_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidincdr',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
