# Generated by Django 2.0.3 on 2018-03-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0008_auto_20180322_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidincdr',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
