# Generated by Django 2.0.3 on 2018-03-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0009_prepaidincdr_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceclass',
            name='inMobilesPercentage',
            field=models.IntegerField(default=50, null=True),
        ),
        migrations.AddField(
            model_name='serviceclass',
            name='isRevenueShare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceclass',
            name='otherOperatorPercentage',
            field=models.IntegerField(default=50, null=True),
        ),
    ]
