# Generated by Django 2.0.3 on 2018-03-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0009_auto_20180325_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueconfig',
            name='timeDuration',
            field=models.IntegerField(default=30),
        ),
    ]
