# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0010_auto_20180404_0334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulkLoader',
        ),
    ]
