# Generated by Django 2.0.3 on 2018-03-23 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0011_auto_20180323_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freebies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 1, 490690, tzinfo=utc))),
                ('updatedDate', models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 1, 490718, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='beepcdr',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 1, 489579, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='beepcdr',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 1, 489602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daincdrmap',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 1, 488958, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daincdrmap',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 1, 488983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 1, 486156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 1, 486182, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 1, 487594, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 1, 487623, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 1, 488260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 1, 488287, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenueconfig',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 1, 490246, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenueconfig',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 1, 490275, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 1, 485604, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 1, 485636, tzinfo=utc)),
        ),
    ]
