# Generated by Django 2.0.3 on 2018-03-23 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0012_auto_20180323_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreebiesType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 609922, tzinfo=utc))),
                ('updatedDate', models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 609973, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='beepcdr',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 608188, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='beepcdr',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 608233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daincdrmap',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 607551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daincdrmap',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 607576, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 604626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 604655, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 606142, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 606169, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='freebies',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 609357, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='freebies',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 609395, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 606831, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 606855, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenueconfig',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 608892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenueconfig',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 608918, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 604081, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 3, 49, 604110, tzinfo=utc)),
        ),
    ]
