# Generated by Django 2.0.3 on 2018-03-23 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0013_auto_20180323_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beepcdr',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 562892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='beepcdr',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 562919, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daincdrmap',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 562256, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daincdrmap',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 562281, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 559448, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 559473, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 559945, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 559971, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='freebies',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 563955, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='freebies',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 563981, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='freebiestype',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 564356, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='freebiestype',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 564388, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 561512, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 561539, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenueconfig',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 563408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenueconfig',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 563433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 558902, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 6, 46, 558932, tzinfo=utc)),
        ),
    ]
