# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0013_prepaidincdr_subscribertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='freebies',
            name='id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
