# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0014_auto_20180404_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='freebies',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
