# Generated by Django 2.0.3 on 2018-03-23 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0014_auto_20180323_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beepcdr',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 293377, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='beepcdr',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 293400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daincdrmap',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 292752, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daincdrmap',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 292777, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 290048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 290074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 291389, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 291418, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='freebies',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 294390, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='freebies',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 294418, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='freebiestype',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 294779, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='freebiestype',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 294804, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 292050, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 292073, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenueconfig',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 293958, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenueconfig',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 293988, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 289515, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 4, 289545, tzinfo=utc)),
        ),
    ]
