# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0015_auto_20180404_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidincdr',
            name='MICRevenue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
