# Generated by Django 2.0.3 on 2018-03-23 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0015_auto_20180323_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beepcdr',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 267065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='beepcdr',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 267091, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daincdrmap',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 266457, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daincdrmap',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 266482, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 263504, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 263529, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 265045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 265071, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='freebies',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 268068, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='freebies',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 268096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='freebiestype',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 268458, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='freebiestype',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 268483, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 265753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 265776, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenueconfig',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 267646, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenueconfig',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 267671, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 262973, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 12, 8, 12, 263003, tzinfo=utc)),
        ),
    ]
