# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0017_auto_20180415_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beepcdr',
            name='callStartTime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='msisdn',
            field=models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='callStartTime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='createdDate',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='inMobilesPercentage',
            field=models.IntegerField(db_index=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='isRevenueShare',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='updatedDate',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
