# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0018_auto_20180415_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMgr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('endPoint', models.CharField(blank=True, max_length=240, null=True)),
                ('nextRunTime', models.DateTimeField()),
                ('lastRunTime', models.DateTimeField()),
                ('interval', models.IntegerField()),
                ('lastRunStatus', models.CharField(default=b'Successful', max_length=20)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.CharField(default=b'Khal Drogo', max_length=240)),
                ('updatedBy', models.CharField(default=b'Khal Drogo', max_length=240)),
            ],
        ),
    ]
