# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0020_schedulemgr_lastreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='testModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'gautam', max_length=10)),
            ],
        ),
    ]
