# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0021_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidincdr',
            name='accountValueAfterCall',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prepaidincdr',
            name='accountValueBeforeCall',
            field=models.FloatField(null=True),
        ),
    ]
