# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0023_auto_20180419_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrepaidInCdr',
            new_name='InCdr',
        ),
        migrations.RenameField(
            model_name='daincdrmap',
            old_name=b'PrepaidInCdr',
            new_name='InCdr',
        ),
    ]
