# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0024_auto_20180423_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkLoadFailedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdr', models.TextField()),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploadedBy', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BulkLoadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('initialCount', models.IntegerField()),
                ('errorCount', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('uploadedBy', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bulkloadfailedlist',
            name='BulkLoadHistory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmb.BulkLoadHistory'),
        ),
    ]
