# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0026_auto_20180424_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkloadhistory',
            name='status',
            field=models.CharField(default='InProgress', max_length=20),
            preserve_default=False,
        ),
    ]
