# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0027_bulkloadhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkloadfailedlist',
            name='cdr',
            field=models.TextField(null=True),
        ),
    ]
