# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0028_auto_20180427_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkloadfailedlist',
            name='error',
            field=models.CharField(default='nothing', max_length=250),
            preserve_default=False,
        ),
    ]
