# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmb', '0031_auto_20180429_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroles',
            name='users',
        ),
        migrations.AddField(
            model_name='userroles',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
