# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0032_auto_20180429_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroles',
            old_name='users',
            new_name='user',
        ),
    ]
