# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0033_auto_20180429_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='createdBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
