# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0034_auto_20180429_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='roles',
            field=models.ManyToManyField(null=True, to='cmb.Roles'),
        ),
    ]
