# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0036_auto_20180506_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='roles',
            field=models.ManyToManyField(blank=True, to='cmb.Roles'),
        ),
    ]
