# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-13 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0037_auto_20180506_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daincdrmap',
            name='InCdr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dedicatedAccounts', to='cmb.InCdr'),
        ),
        migrations.AlterField(
            model_name='incdr',
            name='callCharge',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='incdr',
            name='callStartTime',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='incdr',
            name='calledNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incdr',
            name='callerNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incdr',
            name='chargedDuration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='incdr',
            name='serviceClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmb.ServiceClass'),
        ),
    ]
