# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-13 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0038_auto_20180513_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daincdrmap',
            name='InCdr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dedicatedAccounts', to='cmb.InCdr'),
        ),
        migrations.AlterField(
            model_name='incdr',
            name='callStartTime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
