# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-13 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0039_auto_20180513_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incdr',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
