# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-17 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0040_auto_20180513_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beepcdr',
            name='calledNumber',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='beepcdr',
            name='callerNumber',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='daincdrmap',
            name='dedicatedAccount',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='incdr',
            name='calledNumber',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incdr',
            name='callerNumber',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incdr',
            name='subscriberType',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
