# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-26 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0041_auto_20180517_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beepcdr',
            name='createdBy',
            field=models.CharField(default=b'Premium App', max_length=50),
        ),
        migrations.AlterField(
            model_name='beepcdr',
            name='updatedBy',
            field=models.CharField(default=b'Premium App', max_length=50),
        ),
        migrations.AlterField(
            model_name='daincdrmap',
            name='createdBy',
            field=models.CharField(default=b'Premium App', max_length=100),
        ),
        migrations.AlterField(
            model_name='daincdrmap',
            name='updatedBy',
            field=models.CharField(default=b'Premium App', max_length=100),
        ),
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='createdBy',
            field=models.CharField(default=b'Premium App', max_length=100),
        ),
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='updatedBy',
            field=models.CharField(default=b'Premium App', max_length=100),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='createdBy',
            field=models.CharField(default=b'Premium App', max_length=50),
        ),
        migrations.AlterField(
            model_name='exceptionlist',
            name='updatedBy',
            field=models.CharField(default=b'Premium App', max_length=50),
        ),
        migrations.AlterField(
            model_name='freebies',
            name='createdBy',
            field=models.CharField(default=b'Premium App', max_length=50),
        ),
        migrations.AlterField(
            model_name='freebies',
            name='updatedBy',
            field=models.CharField(default=b'Premium App', max_length=50),
        ),
        migrations.AlterField(
            model_name='freebiestype',
            name='createdBy',
            field=models.CharField(default=b'Premium App', max_length=50),
        ),
        migrations.AlterField(
            model_name='freebiestype',
            name='updatedBy',
            field=models.CharField(default=b'Premium App', max_length=50),
        ),
        migrations.AlterField(
            model_name='incdr',
            name='createdBy',
            field=models.CharField(default=b'Premium App', max_length=50),
        ),
        migrations.AlterField(
            model_name='incdr',
            name='updatedBy',
            field=models.CharField(default=b'Premium App', max_length=50),
        ),
        migrations.AlterField(
            model_name='revenueconfig',
            name='createdBy',
            field=models.CharField(default=b'Premium App', max_length=50),
        ),
        migrations.AlterField(
            model_name='revenueconfig',
            name='updatedBy',
            field=models.CharField(default=b'Premium App', max_length=50),
        ),
        migrations.AlterField(
            model_name='schedulemgr',
            name='createdBy',
            field=models.CharField(default=b'Premium App', max_length=240),
        ),
        migrations.AlterField(
            model_name='schedulemgr',
            name='updatedBy',
            field=models.CharField(default=b'Premium App', max_length=240),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='createdBy',
            field=models.CharField(default=b'Premium App', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='updatedBy',
            field=models.CharField(default=b'Premium App', max_length=50),
        ),
    ]
