# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-01 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0042_auto_20180526_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueconfig',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
