# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-04 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0043_revenueconfig_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='revenueCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriberType', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('createdDate', models.DateTimeField()),
                ('updatedDate', models.DateTimeField()),
            ],
        ),
    ]
