# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-13 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb', '0044_revenuecalculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenueconfig',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
